name: Rancher Documentation
description: Documentation for Rancher


URL: http://rancher.local
baseurl: "/docs"

exclude: []

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty

gems:
  - jekyll-redirect-from
